name: Bug Report
description: Report a bug or issue in the website
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!
  - type: textarea
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots if applicable.
  - type: input
    attributes:
      label: Browser & Device
      description: Which browser and device (desktop/mobile)?
